onEvent('recipes', event => {
  event.remove({output: 'thermal:bronze_ingot'})
  event.remove({output: 'thermal:bronze_block'})
  event.remove({output: 'thermal:bronze_plate'})
  event.remove({output: 'thermal:bronze_ingot', type: 'thermal:furnace'})
    event.remove({id: 'thermal:bronze_nugget'})
    event.remove({id: 'create:crafting/logistics/display_link'})
    event.remove({output: 'thermal:electrum_coin', type: 'thermal:press'})
    event.remove({output: 'thermal:electrum_coin', type: 'tconstruct:casting_table'})
    event.remove({id: 'create:crafting/kinetics/spout'})
    event.remove({id: 'create:crafting/kinetics/item_drain'})
    event.remove({id: 'minecraft:ender_eye'})
    event.remove({id: 'tconstruct:smeltery/casting/ender/eye'})
    event.remove({output: 'thermal:copper_plate'})
    event.remove({id: 'create:crafting/kinetics/encased_fan'})
    event.remove({id: 'create:crafting/kinetics/mechanical_press'})
    event.remove({id: 'create:crafting/kinetics/mechanical_mixer'})
    event.remove({id: 'create:crafting/kinetics/millstone'})
    event.remove({id: 'milkyway_core:coppermachine'})
    event.remove({id: 'tconstruct:smeltery/seared/drain'})
    event.remove({id: 'tconstruct:smeltery/casting/seared/smeltery_controller'})
    event.remove({id: 'create:crafting/kinetics/track_station'})
    event.remove({id: 'create:crafting/kinetics/track_observer'})
    event.remove({id: 'create:crafting/kinetics/track_observer_from_other_plates'})
    event.remove({id: 'create:crafting/kinetics/controls'})
    event.remove({id: 'create:crafting/kinetics/track_signal'})
    event.remove({output: 'milkyway_bosses:albeansummoner', type: 'minecraft:crafting'})
    event.remove({output: 'milkyway_bosses:fedoracrystal', type: 'minecraft:crafting'})
    event.remove({output: 'milkyway_bosses:milkgem', type: 'minecraft:crafting'})
    event.remove({output: 'milkyway_bosses:oval_summoner', type: 'minecraft:crafting'})
    event.remove({output: 'milkyway_bosses:svein_summoner', type: 'minecraft:crafting'})
    event.remove({output: 'milkyway_bosses:fehn_summoner', type: 'minecraft:crafting'})
    event.remove({output: 'milkyway_bosses:infinitysummoner', type: 'minecraft:crafting'})
    event.remove({output: 'milkyway_bosses:raconsummoner', type: 'minecraft:crafting'})
    event.remove({output: 'milkyway_bosses:clockworksummoner', type: 'minecraft:crafting'})
    event.remove({output: 'milkyway_bosses:subjectsummoner', type: 'minecraft:crafting'})
    event.remove({output: 'milkyway_bosses:mouldysummoner', type: 'minecraft:crafting'})
    event.remove({output: 'milkyway_bosses:slayersummoner', type: 'minecraft:crafting'})
    event.remove({output: 'milkyway_bosses:romarvicsummoner', type: 'minecraft:crafting'})
    event.remove({output: 'milkyway_bosses:crusadersummoner', type: 'minecraft:crafting'})
    event.remove({output: 'milkyway_bosses:bagelsummoner', type: 'minecraft:crafting'})
    event.remove({output: 'milkyway_bosses:igohera_gem', type: 'minecraft:crafting'})
    event.remove({output: 'milkyway_bosses:flyhighsummoner', type: 'minecraft:crafting'})
    event.remove({output: 'milkyway_bosses:darkninjasummoner', type: 'minecraft:crafting'})
    event.remove({output: 'milkyway_bosses:murphymonsummoner', type: 'minecraft:crafting'})
    event.remove({output: 'milkyway_bosses:mimisummoner', type: 'minecraft:crafting'})
    event.remove({output: 'milkyway_bosses:pouffysummoner', type: 'minecraft:crafting'})
    event.remove({id: 'create:crafting/kinetics/mechanical_saw'})
    event.remove({id: 'create:crafting/kinetics/deployer'})
    event.remove({id: 'create:crafting/kinetics/mechanical_drill'})
    event.remove({id: 'create:crafting/kinetics/item_vault'})
    event.remove({id: 'tconstruct:smeltery/scorched/drain'})
    event.remove({id: 'tconstruct:smeltery/scorched/chute'})
    event.remove({id: 'tconstruct:smeltery/scorched/duct'})
    event.remove({id: 'tconstruct:smeltery/seared/chute'})
    event.remove({id: 'tconstruct:smeltery/seared/duct'})
    event.remove({id: 'tconstruct:smeltery/casting/scorched/foundry_controller'})
})
