onEvent('item.registry', event => {
event.create('blank_manyullyn_cast').texture("kubejs:item/blank_manyullyn_cast").displayName('Blank Manyullyn Cast')
event.create('manyullyn_disc_cast').texture("kubejs:item/manyullyn_disc_cast").displayName('Manyullyn Disc Cast')
event.create('brass_disc').texture("kubejs:item/brass_disc").displayName('Brass Disc')
event.create('crystallised_manyullyn').texture("kubejs:item/crystallised_manyullyn").displayName('Crystallised Manyullyn')
event.create('andesite_disc').texture("kubejs:item/andesite_disc").displayName('Andesite Disc')
event.create('unpressed_manyullyn_disc_cast').texture("kubejs:item/unpressed_manyullyn_disc_cast").displayName('Unpressed Manyullyn Disc Cast')
event.create('creative_alloy').texture("kubejs:item/creative_alloy").displayName('Creative Alloy')
event.create('creative_alloy_plating').texture("kubejs:item/creative_alloy_plating").displayName('Creative Alloy Plating')
event.create('manyullyn_ingot_cast').texture("kubejs:item/manyullyn_ingot_cast").displayName('Manyullyn Ingot Cast')
event.create('unpressed_manyullyn_ingot_cast').texture("kubejs:item/unpressed_manyullyn_ingot_cast").displayName('Unpressed Manyullyn Ingot Cast')
event.create('creativity_ingot').texture("kubejs:item/creative_ingot").displayName('Creativity Ingot')
event.create('insulated_ingot').texture("kubejs:item/insulated_ingot").displayName('Insulation Cube')
event.create('insulated_plate').texture("kubejs:item/insulated_plate").displayName('Insulation Plate')
event.create('crude_insulator').texture("kubejs:item/crude_insulator").displayName('Crude Insulator')
event.create('unprocessed_insulation_cube').texture("kubejs:item/unprocessed_insulation_cube").displayName('Unprocessed Insulation Cube')
event.create('zinc_dust').texture("kubejs:item/zinc_dust").displayName('Zinc Dust')
event.create('data_tube').texture("kubejs:item/data_tube").displayName('Data Tube')
event.create('incomplete_basic_mechanism').texture("kubejs:item/incomplete_basic_mechanism").displayName('Incomplete Basic Mechanism')
event.create('incomplete_logic_mechanism').texture("kubejs:item/incomplete_logic_mechanism").displayName('Incomplete Logic Mechanism')
event.create('incomplete_copper_mechanism').texture("kubejs:item/incomplete_copper_mechanism").displayName('Incomplete Copper Mechanism')
event.create('incomplete_manyullyn_mechanism').texture("kubejs:item/incomplete_manyullyn_mechanism").displayName('Incomplete Manyullyn Mechanism')
event.create('incomplete_cobalt_mechanism').texture("kubejs:item/incomplete_cobalt_mechanism").displayName('Incomplete Cobalt Mechanism')
event.create('incomplete_basic_mechanism_33').texture("kubejs:item/basic_33").displayName('Incomplete Basic Mechanism')
event.create('incomplete_basic_mechanism_66').texture("kubejs:item/basic_66").displayName('Incomplete Basic Mechanism')
event.create('incomplete_basic_mechanism_99').texture("kubejs:item/basic_99").displayName('Incomplete Basic Mechanism')
event.create('enderium_pearl').texture("kubejs:item/enderium_pearl").displayName('Enderium Pearl')
event.create('slightly_drained_enderium_pearl').texture("kubejs:item/slightly_drained_enderium_pearl").displayName('Slightly Drained Enderium Pearl')
event.create('drained_enderium_pearl').texture("kubejs:item/drained_enderium_pearl").displayName('Drained Enderium Pearl')
event.create('very_drained_enderium_pearl').texture("kubejs:item/very_drained_enderium_pearl").displayName('Very Drained Enderium Pearl')
event.create('enderium_core').texture("kubejs:item/enderium_core").displayName('Enderium Core')
event.create('raw_bauxite').texture("kubejs:item/raw_aluminium").displayName('Raw Bauxite')
event.create('particleboard').texture("kubejs:item/particleboard").displayName('Particle-board')
event.create('blood').texture("kubejs:item/blood").displayName('Hephaestus Blood')
event.create('soul').texture("kubejs:item/soul").displayName('Hephaestus Soul')
event.create('aureal').texture("kubejs:item/aureal").displayName('Hephaestus Aureal')
event.create('experience').texture("kubejs:item/experience").displayName('Hephaestus Experience')
event.create('amethyst_steel').texture("kubejs:item/amethyst_steel").displayName('Amethyst Steel')
event.create('incomplete_seared_mechanism').texture("kubejs:item/incomplete_seared_mechanism").displayName('Incomplete Seared Mechanism')
event.create('diamond_quartz').texture("kubejs:item/diamond_quartz").displayName('Diamond Quartz')
event.create('polished_diamond_quartz').texture("kubejs:item/polished_diamond_quartz").displayName('Polished Diamond Quartz')
event.create('tech_tube').texture("kubejs:item/tech_tube").displayName('Tech Tube')
event.create('aluminium_nugget').texture("kubejs:item/aluminium_nugget").displayName('Aluminium Nugget')
event.create('incomplete_scorched_mechanism').texture("kubejs:item/incomplete_scorched_mechanism").displayName('Incomplete Scorched Mechanism')
event.create('aluminium_dust').texture("kubejs:item/aluminium_dust").displayName('Aluminium Dust')
event.create('amethyst_clump').texture("kubejs:item/amethyst_clump").displayName('Amethyst Clump')
event.create('basalt_rod').texture("kubejs:item/basalt_rod").displayName('Basalt Rod')
event.create('kermitamine').texture("kubejs:item/kermitamine").displayName('Kermitamine')
event.create('kermitamine_tray').texture("kubejs:item/kermitamine_tray").displayName('Kermitamine Tray')
event.create('kermitamine_crystal').texture("kubejs:item/kermitamine_crystal").displayName('Kermitamine Crystal')
event.create('kermitamine_dust').texture("kubejs:item/kermitamine_dust").displayName('Kermitamine Dust')
event.create('solid_kermitamine_233').texture("kubejs:item/solid_kermitamine_233").displayName('Solid Kermitamine-233')
event.create('netherite_queens_slime_catalyst').texture("kubejs:item/catalyst_1").displayName("Netherite-Queen's Slime Catalyst")
event.create('incomplete_tech_tube').texture("kubejs:item/incomplete_tech_tube").displayName('Incomplete Tech Tube')
event.create('incomplete_redstone_flux_coil').texture("kubejs:item/incomplete_redstone_flux_coil").displayName('Incomplete Redstone Flux Coil')
event.create('blank_tablet').texture("kubejs:item/blank_tablet").displayName('Blank Tablet')
event.create('runic_tablet').texture("kubejs:item/runic_tablet").displayName('Runic Tablet')
event.create('arcane_tablet').texture("kubejs:item/arcane_tablet").displayName('Arcane Tablet')
event.create('incomplete_arcane_tablet').texture("kubejs:item/incomplete_arcane_tablet").displayName('Incomplete Arcane Tablet')
event.create('experienced_tablet').texture("kubejs:item/experienced_tablet").displayName('Experienced Tablet')
event.create('alchemic_tablet').texture("kubejs:item/alchemic_tablet").displayName('Alchemic Tablet')
event.create('incomplete_alchemic_tablet').texture("kubejs:item/incomplete_alchemic_tablet").displayName('Incomplete Alchemic Tablet')
event.create('dark_tablet').texture("kubejs:item/dark_tablet").displayName('Dark Tablet')
event.create('damaged_dark_tablet').texture("kubejs:item/damaged_dark_tablet").displayName('Damaged Dark Tablet')
event.create('cracked_dark_tablet').texture("kubejs:item/cracked_dark_tablet").displayName('Cracked Dark Tablet')
event.create('shattered_dark_tablet').texture("kubejs:item/shattered_dark_tablet").displayName('Shattered Dark Tablet')
event.create('pure_tablet').texture("kubejs:item/pure_tablet").displayName('Pure Tablet')
event.create('incomplete_pure_lens_tablet').texture("kubejs:item/incomplete_pure_lens_tablet").displayName('Incomplete Pure Lens Tablet')
event.create('pure_lens_tablet').texture("kubejs:item/pure_lens_tablet").displayName('Pure Lens Tablet')
event.create('incomplete_action_mechanism').texture("kubejs:item/incomplete_action_mechanism").displayName('Incomplete Action Mechanism')
event.create('action_mechanism').texture("kubejs:item/action_mechanism").displayName('Action Mechanism')
//rohbust's items :)

event.create('incomplete_item_pipe').texture("assets/kubejs/models/item/incomplete_item_pipe.png").displayName('Incomplete Item Pipe')
event.create('incomplete_fluid_pipe').texture("assets/kubejs/models/item/incomplete_fluid_pipe.png").displayName('Incomplete Fluid Pipe')

//Item pipe upgrades

event.create('improved_item_pipe_upgrade').texture("kubejs:item/improved_item_pipe_upgrade").tooltip('Right click on item pipe to upgrade').displayName('Improved Item Pipe Upgrade')
event.create('advanced_item_pipe_upgrade').texture("kubejs:item/advanced_item_pipe_upgrade").tooltip('Right click on item pipe to upgrade').displayName('Advanced Item Pipe Upgrade')

//Fluid pipe upgrades

event.create('improved_fluid_pipe_upgrade').texture("kubejs:item/improved_fluid_pipe_upgrade").displayName('Improved Fluid Pipe Upgrade').tooltip('Right click on fluid pipe to upgrade')
event.create('advanced_fluid_pipe_upgrade').texture("kubejs:item/advanced_fluid_pipe_upgrade").displayName('Advanced Fluid Pipe Upgrade').tooltip('Right click on fluid pipe to upgrade')
event.create('elite_fluid_pipe_upgrade').texture("kubejs:item/elite_fluid_pipe_upgrade").displayName('Elite Fluid Pipe Upgrade').tooltip('Right click on fluid pipe to upgrade')
event.create('ultimate_fluid_pipe_upgrade').texture("kubejs:item/ultimate_fluid_pipe_upgrade").displayName('Ultimate Fluid Pipe Upgrade').tooltip('Right click on fluid pipe to upgrade')
})
onEvent('block.registry', event => {
  event.create('manyullyn_casing')
  	   .material('metal')
       .hardness(50)
       .displayName('Manyullyn Casing') // No longer required in 1.18.2+
       .tagBlock('minecraft:mineable/pickaxe') // Make it mine faster using a shovel in 1.18.2+
       event.create('creative_casing')
            .material('metal')
            .hardness(50)
            .displayName('Creative Casing') // No longer required in 1.18.2+
            .tagBlock('minecraft:mineable/pickaxe') // Make it mine faster using a shovel in 1.18.2+
            event.create('insulation_block')
                 .material('wool')
                 .hardness(10)
                 .displayName('Insulation Block') // No longer required in 1.18.2+
                 .tagBlock('minecraft:mineable/axe') // Make it mine faster using a shovel in 1.18.2+
})
