import mods.create.SequencedAssemblyManager;
<recipetype:create:sequenced_assembly>.addRecipe(<recipetype:create:sequenced_assembly>.builder("basic_mechanism")
                                                      .transitionTo(<item:kubejs:incomplete_basic_mechanism>)
                                                      .require(<item:tconstruct:pattern>)
                                                      .loops(1)
                                                      .addOutput(<item:milkyway_core:basic_mechanism> * 1, 32)
                                                      .addOutput(<item:create:andesite_alloy>, 2)
                                                      .addOutput(<item:minecraft:andesite>, 1)
                                                      .addOutput(<item:create:cogwheel>, 1)
                                                      .addOutput(<item:minecraft:stick>, 1)
                                                      .addOutput(<item:minecraft:iron_nugget>, 1)
                                                      .addStep<mods.createtweaker.DeployerApplicationRecipe>((rb) => rb.require(<item:create:andesite_alloy>))
                                                      .addStep<mods.createtweaker.DeployerApplicationRecipe>((rb) => rb.require(<item:createaddition:iron_wire>)));
<recipetype:create:sequenced_assembly>.addRecipe(<recipetype:create:sequenced_assembly>.builder("copper_mechanism")
                                                      .transitionTo(<item:kubejs:incomplete_copper_mechanism>)
                                                      .require(<item:milkyway_core:basic_mechanism>)
                                                      .loops(1)
                                                      .addOutput(<item:milkyway_core:copper_mechanism> * 1, 32)
                                                      .addOutput(<item:alloyed:bronze_sheet>, 2)
                                                      .addOutput(<item:create:copper_nugget>, 1)
                                                      .addOutput(<item:thermal:iron_gear>, 1)
                                                      .addOutput(<item:minecraft:iron_nugget>, 1)
                                                      .addOutput(<item:create:crushed_copper_ore>, 1)
                                                      .addStep<mods.createtweaker.DeployerApplicationRecipe>((rb) => rb.require(<item:alloyed:bronze_sheet>))
                                                      .addStep<mods.createtweaker.DeployerApplicationRecipe>((rb) => rb.require(<item:thermal:iron_gear>))
                                                      .addStep<mods.createtweaker.DeployerApplicationRecipe>((rb) => rb.require(<item:create:copper_sheet>))
                                                      .addStep<mods.createtweaker.PressingRecipe>());
<recipetype:create:sequenced_assembly>.addRecipe(<recipetype:create:sequenced_assembly>.builder("tech_tube")
                                                      .transitionTo(<item:kubejs:incomplete_tech_tube>)
                                                      .require(<item:kubejs:amethyst_steel>)
                                                      .loops(1)
                                                      .addOutput(<item:kubejs:tech_tube> * 1, 32)
                                                      .addOutput(<item:thermal:diamond_dust>, 2)
                                                      .addOutput(<item:thermal:basalz_powder>, 1)
                                                      .addOutput(<item:minecraft:quartz>, 1)
                                                      .addOutput(<item:minecraft:redstone>, 1)
                                                      .addOutput(<item:kubejs:diamond_quartz>, 1)
                                                      .addStep<mods.createtweaker.CuttingRecipe>()
                                                      .addStep<mods.createtweaker.FillingRecipe>((rb) => rb.require(<fluid:thermal:redstone> * 250))
                                                      .addStep<mods.createtweaker.FillingRecipe>((rb) => rb.require(<fluid:thermal:latex> * 500))
                                                      .addStep<mods.createtweaker.DeployerApplicationRecipe>((rb) => rb.require(<item:kubejs:polished_diamond_quartz>))
                                                      );
